# @package _group_
name: NLE
run: sbi.snle.run
device: cpu
params:
  num_rounds: 1
  neural_net: nsf
  hidden_features: 50
  simulation_batch_size: 1000
  training_batch_size: 1000
  automatic_transforms_enabled: true
  mcmc_parameters:
    num_chains: 100
    thin: 10
    warmup_steps: 100
    init_strategy: sir
    sir_batch_size: 100
    sir_num_batches: 1000
  z_score_x: true
  z_score_theta: true
  stop_after_epochs: 20
  validation_fraction: 0.1
  num_transforms: 1
  num_bins: 25
